<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="\css\bootstrap.min.css" rel="stylesheet">
    <script src="\css\bootstrap.bundle.min.js"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
    <header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="\">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link active" href="/">Главная</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="/urls">Сайты</a>
            </li>
        </ul>
        </div>
    </nav>
    </header>

    <?php if (isset($flash['success'])) : ?>
                    <div class="alert alert-success" role="alert">
                    <?= $flash['success'][0] ?>
                    </div>
    <?php endif ?>
    <?php if (isset($flash['error'])) : ?>
                    <div class="alert alert-danger" role="alert">
                    <?= $flash['error'][0] ?>
                    </div>
    <?php endif ?>

    <main class="flex-grow-1">
    <div class="container-lg mt-3">
            <h1>Сайт: <?= htmlspecialchars($url['name']) ?></h1>
            <div class="table-responsive">
            <table class="table table-hover table-bordered text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= htmlspecialchars($url['id']) ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= htmlspecialchars($url['name']) ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= htmlspecialchars($url['created_at']) ?></td>
                    </tr>
            </tbody>
            </table>
            </div>
    </div>
    </main>

    <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="text-center">
                <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
            </div>
        </div>
    </footer>
</body>
</html>