<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href=".\bootstrap\bootstrap.min.css" rel="stylesheet">
    <script src=".\bootstrap\bootstrap.bundle.min.js"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
    <header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="#">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Главная</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#">Сайты</a>
            </li>
        </ul>
        </div>
    </nav>
    </header>

    <main class="flex-grow-1">
    <div class="container-lg mt-3">
    <div class="row">
        <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
            <h1 class="display-3">Анализатор страниц</h1>
            <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
    
            <form action="/urls" method="post" class="row" required="">
                <div class="col-8">
                    <input type="text" class="form-control form-control-lg" id="floatingInputValue" placeholder="https://www.example.com">
                </div>
                <div class="col-2">
                    <button class="btn btn-primary btn-lg text-uppercase ms-3 px-5 mx-3" type="submit">Проверить</button>
                </div>
            </form>
        </div>
    </div>
    </div>
    </main>

    <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="text-center">
                <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
            </div>
        </div>
    </footer>
</body>
</html>