name: linter-check
on: push
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Install project
        run: make install

      - name: Run linter check
        run: make lint